version: "3.8"

services:
  db:
    container_name: postgresql_db
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  test:
    container_name: test
    build: .
    command: pytest
    volumes:
      - .:/app
    depends_on:
      - db
