"""new migrations

Revision ID: 168380d38806
Revises: 5cae6a3964cd
Create Date: 2024-08-04 08:35:11.789939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168380d38806'
down_revision = '5cae6a3964cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
