"""new migrations

Revision ID: 5cae6a3964cd
Revises: 3f933266e63a
Create Date: 2024-08-04 08:32:29.710485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cae6a3964cd'
down_revision = '3f933266e63a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
