"""initial migration

Revision ID: a95f5ea85fd9
Revises: b4e650a3972c
Create Date: 2024-08-02 11:44:17.134196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95f5ea85fd9'
down_revision = 'b4e650a3972c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
